```yaml
name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project to Raspberry Pi
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.PI_USER }}/die-visualizer"

      - name: Restart Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd ~/die-visualizer
            docker build -t dieapp .
            docker rm -f dieapp || true
            docker run -d -p 5000:5000 --name dieapp dieapp
