name:  Deploy to Raspberry Pi via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name:  Deploy over SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/die-visualizer-raspberry
          git pull
          sudo docker build -t dieapp .
          sudo docker stop dieapp || true
          sudo docker rm dieapp || true
          sudo docker run -d -p 5000:5000 --name dieapp dieapp
        EOF
